/**
	react-native can't import files dynamically through generated names 
	than it needs a map of all files in format { '001-003': require('files/001-003.mp3') }
	this node module reads files in /content and writes map of them to /src/assets
 */

const path = require('path')
const { writeFileSyncRecursive } = require('./fsUtils')

const baseDir = './content'

const { getSubDirsOfDir, getFileMapOfDir } = require('./fsUtils')
    // types of files, like: /audio, /images, etc. 
const mediaTypes = getSubDirsOfDir(baseDir)

const mediaMaps = []

mediaTypes.forEach(mediaType => {
    // subchapters (semantic types of files, like: /words, /phrases, etc. )
    const subchapters = getSubDirsOfDir(path.join(baseDir, mediaType))
    subchapters.forEach(subchapter => {
        const mapFiles = getFileMapOfDir(path.join(path.join(baseDir, mediaType, subchapter)))
        mediaMaps.push({ mediaType, subchapter, mapFiles })
    })
})

mediaMaps.forEach(elem => {
    const { mediaType, subchapter } = elem
    const beforeContent = `// autogenerated from /content/${mediaType}/${subchapter} 
// via /src/utils/createMapOfMedia.js
export default `

    const jsString = JSON.stringify(elem.mapFiles, null, "\t").replace(/"(require\(.+\))"/g, '$1').replace(/\\"/g, '"')
    const filePath = `${path.join('./assets', mediaType, subchapter)}.js`
    writeFileSyncRecursive(filePath, beforeContent + jsString, 'utf-8')
})

console.log('maps of media updated')